### ISSUE TITLE
CI seems grumpy

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#218] opened 2021-06-04 09:07 UTC
Hey @rust-lang/infra -- [CI seems to be failing to build the mdbook in this repo](https://github.com/rust-lang/wg-async-foundations/actions/runs/905706759) but it works fine for me locally. I imagine the problem is related to installing mdbook-mermaid based on the errors I'm seeing. Maybe something is wrong with the setup here?

https://github.com/rust-lang/wg-async-foundations/blob/73d94b8b5668c68d96462092030620d63882d610/.github/workflows/ci.yml#L15-L21

Not sure!

**Comment by eminence** [comment] 2021-06-04 13:45
I also cannot reproduce locally, however I *can* reproduce in a local ubuntu docker container.  I haven't done any debugging yet within this container, but I can do that later (if no one else gets to it first)

**Comment by eminence** [comment] 2021-06-11 13:09
The latest mdbook-mermaid release has a fix for this (confirmed by re-running some of the failed CIs on open PRs)

**Closed by eminence** 2021-06-11 13:09 UTC
